plugins {
    id 'fabric-loom' version "${loom_version}"
    id 'maven-publish'
    id("net.ltgt.errorprone") version "4.3.0"
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    // Add repositories to retrieve artifacts from in here.
    // You should only use this when depending on other mods because
    // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
    // See https://docs.gradle.org/current/userguide/declaring_repositories.html
    // for more information about repositories.

    // Serves Polymer modules
    maven {
        url 'https://maven.nucleoid.xyz'
    }
    maven {
        url "https://repo.biryeong.kim/releases/"
    }

    maven {
		url ("https://maven.supersanta.me/snapshots")
	}

	maven {
		url ("https://jitpack.io")
	}
//	maven{
//		url("https://maven.andante.dev/releases/")
//	}
    maven {
        url 'https://kneelawk.com/maven/'
        name 'Kneelawk Maven'
    }
    maven {
        // For LibNetworkStack, if using 'syncing' module
        url 'https://maven.alexiil.uk/'
        name 'AlexIIL Maven'
    }

//     Uncomment if using Rosemary or some other Modrinth dependency
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }

        filter {
            includeGroup "maven.modrinth"
        }
    }
    maven { url "https://maven.tomalbrc.de" }
}


fabricApi {
    configureDataGeneration {
        client = true
    }
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API. This is technically optional, but you probably want it anyway.
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    // Polymer
    modImplementation("eu.pb4:polymer-core:${project.polymer_version}")
    modImplementation("eu.pb4:polymer-virtual-entity:${project.polymer_version}")
    modImplementation("eu.pb4:polymer-resource-pack:${project.polymer_version}")
    modImplementation("eu.pb4:polymer-resource-pack-extras:${project.polymer_version}")
    modImplementation("eu.pb4:polymer-autohost:${project.polymer_version}")
    modImplementation("eu.pb4:polymer-blocks:${project.polymer_version}")

    // Server-Translations
    modImplementation include("xyz.nucleoid:server-translations-api:${project.server_translations_version}")
    modImplementation include("xyz.nucleoid:stimuli:${project.stimuli_version}")

    modImplementation include("net.kyori:adventure-platform-fabric:${project.adventure_platform_version}")
    implementation "net.kyori:adventure-text-minimessage:${project.adventure_api_version}"
    implementation "net.kyori:adventure-api:${project.adventure_api_version}"

    modImplementation("maven.modrinth:danse:2.2.13+1.21.7") {
        exclude module: "de.tomalbrc:blockbench-import-library"
    }
    modImplementation("de.tomalbrc:DialogUtils:${project.dialogutils_version}")
    {
        exclude module: "de.tomalbrc:blockbench-import-library"
    }
    modImplementation include("de.tomalbrc:blockbench-import-library:${project.bli_version}")
    modImplementation include("xyz.nucleoid:fantasy:${project.fantasy_version}")
    modImplementation include("xyz.nucleoid:map-templates:${project.map_templates}")

    // SGUI, you might want this for UI but it depends on your use case
    modImplementation include("eu.pb4:sgui:${project.sgui_version}")
    modImplementation include("me.senseiwells:server-replay:3.0.1+1.21.8")
    // Rosemary, my server-side library.
    // It adds some helpful things like simple configuration and dialog utils, but no need to use if you don't want to.
    // Make sure to add rosemarylib to your dependencies and uncomment the Modrinth repository if you are using it.
//	modImplementation include("de.tomalbrc:DialogUtils:${project.dialogutils_version}")
    modImplementation include("eu.pb4:sidebar-api:${project.sidebar_api_version}")
    modImplementation include("de.tomalbrc:avatar-renderer:${project.avatar_renderer_version}")
    modImplementation include("eu.pb4:map-canvas-api:${project.map_canvas_api_version}")
    modImplementation ("eu.pb4:polydex:1.6.0+1.21.6")
//	modImplementation include("eu.pb4:placeholder-api:${project.papi_version}")
    errorprone("com.google.errorprone:error_prone_core:${project.errorprone_version}")

    modCompileOnly("maven.modrinth:journeymap:1.21.8-6.0.0-beta.52+fabric")
    modCompileOnly("maven.modrinth:xaeros-minimap:fabric-1.21.8-25.3.10")
    modCompileOnly("maven.modrinth:polyfactory:0.8.2+1.21.8")
//    modRuntimeOnly("eu.pb4:PolyFactory:0.8.2+1.21.8") {
//        exclude group: "net.fabricmc.fabric-api", module: "fabric-api"
//        exclude group: "me.lucko", module: "fabric-permissions-api"
//        exclude group: "eu.pb4", module: "*"
//    }
    modImplementation("eu.pb4:factorytools:0.7.5+1.21.8")
    modRuntimeOnly('com.kneelawk.graphlib:graphlib-core-fabric:2.0.3-beta.1+1.21.5')
}

configurations.configureEach {
    exclude group: 'me.lucko', module: 'fabric-permissions-api'
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": inputs.properties.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    inputs.property "archivesName", project.base.archivesName

    from("LICENSE") {
        rename { "${it}_${inputs.properties.archivesName}" }
    }
}

// configure the maven publication
publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
    }

    loom {
        runs {
            datagen {
//			server()
                client()
                name = "Data Generation"
                runDir = "build/datagen"
                vmArg("-Dfabric-api.datagen")
                vmArg("-Dfabric-api.datagen.modid=ttt")
                vmArg("-Dfabric-api.datagen.output-dir=${file("src/main/generated")}")
            }
        }
    }
}

fabricApi {
    configureTests {
        createSourceSet = true
        modId = "mod-test-${project.name}"
        enableGameTests = true
        enableClientGameTests = false
        eula = true
    }
}

tasks.named('runGameTest', JavaExec).configure {
    jvmArgs += [
            "-Dfabric-api.gametest.report-file=${project.buildDir}/junit.xml",
            "-Dmixin.debug.countInjections=true"
    ]
}
